#This is presently just chktex_en.pl with most of the obviously english only
#rules removed. It probably isn't much use for checking french yet.
#Also we may have to pass a special flag to LanguageTool.

my $s='(?:\n|\s)';
our @ErrorTypes=(
 #["Error Name",	"(err[[:space:]]*or.)",	"",  "Error Description"],
#SimpleRule("satisfiable"),
SimpleRule("spelt correctly", "spelled correctly"), #Make Americans Happy.
["Empty mathblock", "$start_math_char  *$end_math_char", '', ""], 
["Macro without {}.", "[^\\\\]\\\\[[:alnum:]]+CTL[[:alnum:]]+\\s", '', "You should probably put a {} after the macro so as not to swallow the space"], 
["Second word in sentance is captialised.", "[.]\\s+[[:alnum:]]+\\s+(?!$capword)[[:upper:]]", '', "When I capitalise the second word of a sentance it is usually a mistake."], 
["no full stop after cite that ends paragraph", "[[:alnum:]]\\s+\\\\cite[{][^}]*[}]\\s*$par", '', "I think a fullstop is missing here."], 
#["[cite] note", "\\\\cite[{][^},]*[}]\\s*note\\b", '', "note -> notes"], #If multiple authors or papers, use "note"?
["No space after cite", "\\\\cite[{][^}]*[}][[:alnum:]]", '', ""], 
["No space before cite", "[[:alnum:]]\\\\cite[{][^}]*[}]", '', ""], 
["Underline starts too early", "\\\\uline[{]\\s", '', ""], 
["Underline ends too late", "\\\\uline[{][^}]\\s[}]", '', ""], 
["Space before foot-note", "(?: %\\s+| )\\\\footnote[{]", '', ""], # BTW footnotes are described at http://www.bristol.ac.uk/arts/exercises/referencing/referencing%20skills/page_07.htm
["Period/Comma after foot-note", "\\\\footnote$recursive_brace".'[.,]', '', "If the foot note refers to the sentance as a whole it is normal to put the foot-note after the fullstop"], # BTW footnotes are described at http://www.bristol.ac.uk/arts/exercises/referencing/referencing%20skills/page_07.htm
["Double Punctuation", '(?<!\\\\)[,.:;]\\s+[,.:;]','',""],
["Use of implies for forward direction in proof", '(?:(?:\\\\left)?[(]\\\\implies(?:\\\\right)?[)]|[(].\\\\implies.[)])','',"Using (\\implies) leaves an ugly space between the arrow and the brackets. When indicating the forward direction of a proof it is probably better to use '(\\Longrightarrow)' instead"],
["No space after reference", 'ref[{][^}]*[}][[:alnum:]]', "", ""],
["Single char", '\s[b-z]\s(?![&\\\\])'."(?![^$start_math_char]*[_$end_math_char])", "", "?"],
["Captial without preceeding fullstop", "(?!(?:on|of|to|with)\\b)(?:$lowerword|ref[{][^{}]*[}]),?:?(?:(%.*\n)|\\s)+(?!$capword)([[:upper:]][[:alnum:]]*)", "erase:(?:\\\\(?:chapter|(?:sub)*section[*]?$recursive_brace)|$mathblock)", "ARG2~CAP, 1;ARG1, 2;ARG2"],
["Empty Begin/End Block", "\\\\begin[{][^}]+[}]\\s*(?:\\\\par)?\\\\end[{][^}]*[}]", "Perhaps you mean *is* thus a?"],
["Proof starting not on newline", '.+\\\\begin[{]proof[}]', "It seems that you don't have a paragraph break between the Lemma/Theorem and the proof \n (you can use the \"Enter\" key in LyX GUI to add one)"],
["No space between text and reference", '[[:alnum:]]\\\\(pretty)?ref[{]', "Perhaps you should add a non-breaking space \n('~' or Ctrl-Space in the LyX GUI)\n between the text and the reference?"],
["No space between text and reference", '^.(?:pretty)?ref[{]', "Perhaps you should add a non-breaking space \n('~' or Ctrl-Space in the LyX GUI)\n between the text and the reference?"],
[". .", '[.]\s+[.]', "Why do you have more than one '.'?"],
[". .", '[.][ ][.]', "Why do you have more than one '.'(2)?"],
["^.\\s+[[:upper:]]", "^.\\s+[[:upper:]]", "Why do you have more than one '.'(3)?"],
["^.\\s+[[:upper:]]", '[.][ ][.]', "Why do you have more than one '.'(3)?"],
["space between cite and punctuation","\\\\cite[{][^{}]*[}]\\s+[,.]","", ''],
[".Capital",'[.][[:upper:]][^.]',"", 'Perhaps you should put a space between the . and the captial'],
[".word",'[.][[:lower:]]+[[:space:]]',"", 'Perhaps you should put a space between the . and the word'],
['\\textquotedbl[{][}]','\\\\textquotedbl[{][}]',"", "You should probably use `` or '' instead of \\textquotedbl{} or ".'"'],
["Space between mathblock and punctuation",$mathblock.'\s+[,.]',"", 'Why is there a capital after the mathblock?'],
["Inapproriate captial after mathblock",'[[:alnum:]] '.$mathblock.' (?!'.$capword.')(?!Robustly)[[:upper:]]',"", 'Why is there a capital after the mathblock?'],
["Equals outside mathblock",	$mathblock.'\s*=\s*'.$mathblock,"", 'Perhaps you should put the equals inside the mathblocks'],
["No space before math block",	"[[:alnum:]]$start_math(?![_^]|\\\\.dots)",	"", ""],
["No space before citation",	"[^[:space:](~]\\\\cite",	"", ""],
#["Number of (singular)",	"[Nn]umber\\s+of\\s+[[:alnum:]]+[^s\\s]\\b",	"", ""],
["Capital following comma",	",\\s*(?!b|$names|Coomb|Hare\\b|Marquis\\b||Khachian\\b|Dominating\\s+Set\\b\\b|Impartial\\s+Culture\\b)[[:upper:]][[:lower:]]",	'Remove capitals from beginning of ARG1', ""],
["Inappropriate capital",	'[^ 
.?:}](?<![.]\'\')(?<![.]\')(?<![.]")\\s+It',	'Remove capital', ""],
["Footnote is not fullstop",   "[[:alnum:],]\\s*\\\\footnote$recursive_brace\\\\s*[[:upper:]]",'',''],
["Footnote is not fullstop",   "[[:alnum:],](\\s|%
)*\\\\footnote$recursive_brace\\s*[[:upper:]]",'',''],
["No space after math block",	'(?!..sim)'.$mathblock.'(?<!dots.)(?!s\s)[[:alnum:]]',	"..sim", ""],
["No space before macro",	"[[:alnum:]]$macroblock",	"", ""],
["No space after macro",	$macroblock.'[[:alnum:]]',	"", ""],
["A used for plural",	'\\b[Aa]\\s+sequences\\b',	"", ""],
#["Comma following footnote",	'\\\\footnote[{][^}]*[}],',	"", ""],
["Use of : in math-mode",	$start_math_char.'[^'.$end_math_char.']*(?<![\\\\])[[:alpha:]]:',	"", "LaTeX assumes a : in mathmode means division, if you are trying to define a function, you should use \\colon instead."],
["less that",	'\\bless\\s+that\\b',	"", ""],
["Ugly fraction",		"([[:digit:]])/([[:digit:]])(?!n[}])(?!_home)",	"erase:\\\\url$recursive_brace", "Use \\nicefrac\{ARG1\}\{ARG2\} instead"],
["Too many zeros without a comma",		"(?<!.)0000(?![^\\s]*[.]tex[}])",	"", "You should put a comma in there somewhere"],
["Duplicated Words",	'(?i)\b([[:alpha:]]+)\b[,.;]?\s+\b\2\b'.$notinmath,	'ARG1 occurs twice.', ""],
["Duplicated Words (broken)",	'(?i)\b(?![[:alpha:]]+\s+by|more\s+and|sets\s+of|that\s+|is\s+|may\s+or|does\s+or\s+does\s+not|neck\s+and\s+neck|as\s+well\s+as|(?:as|of|to)\s)([[:alpha:]]+)\s+(?!to)[[:alpha:]]+\s+\2\b(?![{-])',	'ARG1 occurs twice.', ""],
["Paragraph should end in fullstop","[[:alnum:]](?<!iffalse)(?<!maketitle)(?<!medskip)(?<!hline)(?<![[:upper:]]{3})(?>!\\\\else)(?<![\\\\]fi)[[:space:]]*\n\n",	"", ""],
["Paragraph should start with captial",$par."[[:lower:]]",	"", ""],
["Paragraph starts with fullstop?",$par."\\.",	"", ""],
["Place punctuation outside mathmode",".([,.:?])$end_math",	"", "Move ARG1 out of math mode"],
["Double dot", '\. \.',"","You probably only need one dot."],
["Remove space before punctuation","(?<!\\\\)\\b[[:alnum:]]+\\s+(?:\\\\@)?([,.:;?])(?!=)",	"", "Remove Space before ARG1 "],
["Remove space before punctuation[2]","(?<!\\\\)\\b[[:alnum:]]+\\s+(['])",	"", "Remove Space before ARG1... or perhaps you meant to use ` instead of '?"],
["Index entries should start with captial letters","\\\\index[{][[:lower:]]",	"", ""],
["You should use Var()","\\\\[Vv]ari[[]|\\\\sigma[(]|\\\\sigma\\^[{]2[}][(]|\\\\cov[[]","\\bit\\s+that\\b",	"", "In statistics, you should use Var() for variance. Even though you use E[X] instead of E(X). Weird huh?"],
["Use of pretty ref with out prefix",	"\\\\prettyref[{][^}:]*[}]", "", 'If you are using prettyref to cross reference a chapter the label should start with "cha:", if the label is fore a section the label should start with "sec:" etc.'],
["Lemma label without 'lem:'",	"\\\\begin[{]lem[}]\\s+\\\\label[{](?!lem:)", "", 'If you start a Lemma label without lem, prettyref can get confused.'],
["Corollary label without 'cor:'",	"\\\\begin[{]cor[}]\\s+\\\\label[{](?!cor:)", "", 'If you start a Lemma label without lem, prettyref can get confused.'],
["Theorem label without 'thm:'",	"\\\\begin[{]thm[}]\\s+\\\\label[{](?!thm:)", "", 'If you start a Lemma label without lem, prettyref can get confused.'],
["Lack of Lemma prefix",	"\\b(?!Lemma|and)[^\\s~]+[~\\s]+\\\\ref[{]lem:","",""],
["Lack of Corollary prefix",	"\\b(?!Corollary)[^~\\s]+[~\\s]+\\\\ref[{]cor:","",""],
["Lack of Theorem prefix",	"\\b(?!Theorem|and)[^\\s~]+[~\\s]+\\\\ref[{]thm:","",""],
["Use of lowercase reference",	"(lemma|theorem|table|figure|corollary)[~ ]\\\\ref\\b", "", 'The first letter of ARG1 should be capitalised to adhere to the LaTeX \\prettyref standard.'],
["lemma/theorem occurs before prettyref",	"(emma|heorem|xamples|Example|orollary|efinition)\\s+\\\\prettyref\\b", "", 'It is safer to use a Formatted Reference (i.e. \\prettyref), rather than manually format references, as Formatted References will automatically change the reference if you change the object being referenced (e.g. from a lemma to a theorem).'],
["Empty Footnote","\\\\footnote[{](\\s|\n)*[}]","","There is a footnote with nothing in it. Perhaps you should remove it"],
["Section ending with '.'","\\\\(?:sub)*section[{].*[.][}](?:\n|\$)","","It is unusual to have a section that ends with '.'"],
["Space before punctuation", $end_math.'\s+(?:\\\\[@])?([;.,])', "", "There is a space before the end of the mathblock and 'ARG1'"], 
["Forces what?", $end_math.'[({]\\\\forces', "", "In modal logic there should be something other than a bracket before \\forces"], 
["Space before )",$end_math."[^".$start_math."]*\\s\\)", "", ""],
["Lonely End Proof",$par.'[\\\\]end{proof}', "", "You should probably delete the paragraph break before the \\end{proof}"], 
["no full stop at end of definition","[[:alnum:]$end_math]".'\s*.end{definition}',"",""],
["no full stop at end of .*","[[:alnum:]$end_math]".'(?:\s|%[^\n]*)*.end{(?!algorithmic|enum|item|array|eqnarray|align)',"",""]
);
