#!/bin/sh
#This a wrapper around chktex.pl. It traps chktex.pl's output to a debug file.
echo foo > /tmp/foo
ierr=/tmp/chktex.pl.internal_error
export XTERM=`which xterm false | head -n1`
export DEBUGFILE=/tmp/lyx-gc.$USER.DEBUG
export PATH="/bin:/usr/bin:$PATH"

echo -------- START --------- >> $DEBUGFILE
echo -- PARAMS $* >> $DEBUGFILE
echo -- PWD `pwd` >> $DEBUGFILE
errviewer=`which xless gless | head -n1`
$0.pl $* 2> $ierr || [ -z "$errviewer" ] || ( $errviewer $ierr  -geometry 131x10 & )
echo -- PARAMS $* > /tmp/params

