#!/bin/sh
#This is a small shell script that adds lyx-gc.dir to the path so that LyX
#finds our "lyx-gc.dir/chktex" instead of /usr/bin/chktex. It then runs Lyx.
export LANG=en_AU.UTF-8
export ORIG_CHKTEX=`which chktex`


#if we used a symbolic link, retrieve the real script location
if [ -h $0 ]; then
    LYXGC_PATH=$(dirname $(readlink $0))
else
	LYXGC_PATH=$(cd "$(dirname "$0")" && pwd)
fi
LYXGC_PATH=$LYXGC_PATH"/path"

#if LYXGC_PATH directory does not exist, abort
if [ ! -d "$LYXGC_PATH" ]; then
	echo "Folder $LYXGC_PATH does not exist, invalid installation. Please see to https://github.com/gmatht/lyx-gc/"
	exit 1
fi

export PATH=$LYXGC_PATH:$PATH
echo Path used by lyx is: $PATH
if test -z "$LYX";then
	echo b
	LYX=`which i786-pc-linux-gnu-lyx lyx-qt lyx-xforms lyx | head -n1`
fi
export LYX_GUI=qt
echo "$LYX" "$@"
#valgrind "$LYX" "$@"
"$LYX" "$@"
